# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

tits = Category.create(title: "tits", favorite: true)
pussy = Category.create(title: "pussy", favorite: false)
hq = Category.create(title: "high quality", favorite: true)
fullbody = Category.create(title: "full body", favorite: false)
elina = Category.create(title: "elina", favorite: false)
cum = Category.create(title: "cum", favorite: true)
fucking = Category.create(title: "fucking", favorite: false)

tits.images.create(url: "https://i.redd.it/hielq7e3kci61.jpg", title: "02 girl", favorite: true, mediatype: "image")
hq.images.create(url: "https://i.redd.it/4o06qobpyi961.jpg", title: "Carisha Maya", favorite: true, mediatype: "image")
hq.images.create(url: "https://i.redd.it/gf9e6bge0r361.jpg", title: "Irine Meier", favorite: true, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/UyKT1uO.jpg", title: "hotpussyfrombehind", favorite: false, mediatype: "image")
tits.images.create(url: "https://external-preview.redd.it/QaqwQIy1nW0wWeriGvahLurbCvBQnio-PfYPJkWYfNs.jpg?width=960&crop=smart&auto=webp&s=cb4fd95bd6773287c0eb9a46c947e7c278787f21", title: "delicious on off", favorite: true, mediatype: "image")
pussy.images.create(url: "https://i.redd.it/2pggvlr3ayf61.jpg", title: "howsmyform", favorite: true, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/uUBjKNa.jpg", title: "just finished getting fucked", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.redd.it/yxc8cbhi7bz51.jpg", title: "how's the view back there", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.redd.it/z02rapav8b541.png", title: "clean", favorite: true, mediatype: "image")
tits.images.create(url: "https://i.imgur.com/WrDAycO.jpg", title: "fun in the pool", favorite: false, mediatype: "image")
tits.images.create(url: "https://i.redd.it/17tem7uwzex51.jpg", title: "babe", favorite: false, mediatype: "image")
tits.images.create(url: "https://i.imgur.com/bYE6wUD.jpg", title: "babe", favorite: false, mediatype: "image")
tits.images.create(url: "https://i.imgur.com/HliR0Ao.jpg", title: "what about my tits", favorite: true, mediatype: "image")
tits.images.create(url: "https://i.redd.it/b7846xglcm761.jpg", title: "well gifted", favorite: false, mediatype: "image")
hq.images.create(url: "https://i.redd.it/yphl1psyp5c61.jpg", title: "renata ri", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/maDGUik.jpg", title: "made for anal", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/A37VN0E.png", title: "lilit a granat", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.redd.it/ygk744rsybd61.jpg", title: "the boots stay on", favorite: false, mediatype: "image")
tits.images.create(url: "https://i.imgur.com/qfAASBK.jpg", title: "blue hair", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/3MkA1VI.jpg", title: "which hole", favorite: false, mediatype: "image")
hq.images.create(url: "https://i.imgur.com/zlTiQys.jpg", title: "carolina kris", favorite: false, mediatype: "image")
tits.images.create(url: "https://i.redd.it/ck6dd6bemwr41.jpg", title: "sunbathing", favorite: true, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/re33cIb.jpg", title: "delightful folds", favorite: false, mediatype: "image")
pussy.images.create(url: "https://i.imgur.com/9KsyNlr.jpg", title: "dominique", favorite: false, mediatype: "image")
cum.images.create(url: "https://thumbs.gfycat.com/FailingCraftyIbex-mobile.mp4", title: "this made me bust", favorite: true, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/BrightInformalArmyant-mobile.mp4", title: "very clean undercarriage", favorite: false, mediatype: "video")
fucking.images.create(url: "https://thumbs2.redgifs.com/NeglectedWeepyKangaroo.mp4", title: "using her ass", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/GratefulNiftyDodo.mp4", title: "splash", favorite: false, mediatype: "video")
tits.images.create(url: "https://thumbs.gfycat.com/GrotesqueGraciousGrayling-mobile.mp4", title: "perky perfection", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs.gfycat.com/MediocreSparseAnemoneshrimp-mobile.mp4", title: "legendary cumshot", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/RevolvingRelievedConey.mp4", title: "14 spurts no 1", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/DesertedDifficultChupacabra.mp4", title: "14 spurts no 2", favorite: false, mediatype: "video")
pussy.images.create(url: "https://i.imgur.com/u1iSca4.mp4", title: "clover and antonia", favorite: false, mediatype: "video")
pussy.images.create(url: "https://thumbs.gfycat.com/LeanAgreeableIbis-mobile.mp4", title: "blue is her favorite color", favorite: true, mediatype: "video")
tits.images.create(url: "https://thumbs2.redgifs.com/GrimyBleakFeline.mp4", title: "nancy a", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/GenuineCostlyAlleycat.mp4", title: "small effort huge effect", favorite: false, mediatype: "video")
fullbody.images.create(url: "https://thumbs2.redgifs.com/HoarseVerifiableHippopotamus-mobile.mp4", title: "you spying me", favorite: false, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/VictoriousThatBlackandtancoonhound.mp4", title: "watching it build up", favorite: true, mediatype: "video")
pussy.images.create(url: "https://i.imgur.com/COrgu1w.mp4", title: "riding my favorite toy II", favorite: false, mediatype: "video")
tits.images.create(url: "https://i.imgur.com/nUJ6gQE.mp4", title: "jannetfox", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/ShimmeringSinfulGangesdolphin.mp4", title: "sasha makes you cum", favorite: false, mediatype: "video")
tits.images.create(url: "https://i.imgur.com/Z9VI6Ql.mp4", title: "lack of titty drops", favorite: true, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/TenseRightGharial-mobile.mp4", title: "breaking the seal", favorite: true, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/LastingNaiveAfricangoldencat-mobile.mp4", title: "masturbate from this angle", favorite: true, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/MenacingYellowishCanary-mobile.mp4", title: "edging fail", favorite: true, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/BackFrighteningGrayfox.mp4", title: "rubbing her clit", favorite: false, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/ObviousSplendidIndianelephant.mp4", title: "caprice", favorite: false, mediatype: "video")
pussy.images.create(url: "https://thumbs2.redgifs.com/RedGentleFreshwatereel.mp4", title: "alone in the bathroom", favorite: false, mediatype: "video")
fucking.images.create(url: "https://thumbs2.redgifs.com/EnchantedDemandingAsianconstablebutterfly.mp4", title: "the look of a succubus", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/HelplessFlamboyantEarthworm-mobile.mp4", title: "natalie ray bukkake", favorite: false, mediatype: "video")
cum.images.create(url: "https://thumbs2.redgifs.com/CoolDependableHerald.mp4", title: "sticky facial", favorite: false, mediatype: "video")
